FROM mysql:8.0.33
# RUN apt-get update -y
# COPY my.conf /etc/mysql/conf.d 
# COPY create-table.sql /docker-entrypoint-initdb.d  # create-tabale.sqlはCREATE TABLE文が書かれたファイル
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=yuto
ENV MYSQL_DATABASE=quest
ENV MYSQL_PASSWORD=yutosql
ENV MYSQL_PASSWORD=yutosql
